package com.example.demo.entity;

import java.util.Date;

public class Demo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.sex
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.age
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.birthday
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.sex
     *
     * @return the value of demo.sex
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.sex
     *
     * @param sex the value for demo.sex
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.age
     *
     * @return the value of demo.age
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.age
     *
     * @param age the value for demo.age
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.birthday
     *
     * @return the value of demo.birthday
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.birthday
     *
     * @param birthday the value for demo.birthday
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}