package com.example.demo.entity;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.ID
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TITLE
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.ID
     *
     * @return the value of test.ID
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.ID
     *
     * @param id the value for test.ID
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TITLE
     *
     * @return the value of test.TITLE
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TITLE
     *
     * @param title the value for test.TITLE
     *
     * @mbg.generated Mon Apr 27 23:02:39 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}