package com.example.demo.entity;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.userName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.passWord
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.realName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    private String realname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.userName
     *
     * @return the value of test.userName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.userName
     *
     * @param username the value for test.userName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.passWord
     *
     * @return the value of test.passWord
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.passWord
     *
     * @param password the value for test.passWord
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.realName
     *
     * @return the value of test.realName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.realName
     *
     * @param realname the value for test.realName
     *
     * @mbg.generated Tue Mar 31 20:08:12 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }
}