package com.example.demo.entity;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TYPEID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TYPE_NAME
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TYPEID
     *
     * @return the value of type.TYPEID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TYPEID
     *
     * @param typeid the value for type.TYPEID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TYPE_NAME
     *
     * @return the value of type.TYPE_NAME
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TYPE_NAME
     *
     * @param typeName the value for type.TYPE_NAME
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}