package com.example.demo.entity;

public class UpFan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_fan.UPID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    private String upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_fan.FANID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    private String fanid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_fan.UPID
     *
     * @return the value of up_fan.UPID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public String getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_fan.UPID
     *
     * @param upid the value for up_fan.UPID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public void setUpid(String upid) {
        this.upid = upid == null ? null : upid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_fan.FANID
     *
     * @return the value of up_fan.FANID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public String getFanid() {
        return fanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_fan.FANID
     *
     * @param fanid the value for up_fan.FANID
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    public void setFanid(String fanid) {
        this.fanid = fanid == null ? null : fanid.trim();
    }
}