package com.example.demo.mapper;

import com.example.demo.entity.ArticleType;
import com.example.demo.entity.ArticleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    long countByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    int deleteByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    List<ArticleType> selectByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri May 01 15:16:22 CST 2020
     */
    int updateByExample(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);
}