package com.example.demo.mapper;

import com.example.demo.entity.UserArticle;
import com.example.demo.entity.UserArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    long countByExample(UserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    int deleteByExample(UserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    int insert(UserArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    int insertSelective(UserArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    List<UserArticle> selectByExample(UserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserArticle record, @Param("example") UserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_article
     *
     * @mbg.generated Fri Apr 24 15:59:50 CST 2020
     */
    int updateByExample(@Param("record") UserArticle record, @Param("example") UserArticleExample example);
}